Slurm job started at 18/06/2023_20:09:12

NNODES = 4
SIMUNODES = 2
WORKERNODES = 2
NPROC = 4
NWORKER = 60
..['tcp://10.7.0.132:32995', 'tcp://10.7.0.132:33698', 'tcp://10.7.0.132:34494', 'tcp://10.7.0.132:34554', 'tcp://10.7.0.132:35639', 'tcp://10.7.0.132:35771', 'tcp://10.7.0.132:35992', 'tcp://10.7.0.132:36392', 'tcp://10.7.0.132:36899', 'tcp://10.7.0.132:37477', 'tcp://10.7.0.132:38145', 'tcp://10.7.0.132:39014', 'tcp://10.7.0.132:39340', 'tcp://10.7.0.132:39407', 'tcp://10.7.0.132:39881', 'tcp://10.7.0.132:40275', 'tcp://10.7.0.132:40288', 'tcp://10.7.0.132:40918', 'tcp://10.7.0.132:41734', 'tcp://10.7.0.132:42069', 'tcp://10.7.0.132:42147', 'tcp://10.7.0.132:42329', 'tcp://10.7.0.132:43170', 'tcp://10.7.0.132:43916', 'tcp://10.7.0.132:44252', 'tcp://10.7.0.132:44398', 'tcp://10.7.0.132:44815', 'tcp://10.7.0.132:45928', 'tcp://10.7.0.132:46090', 'tcp://10.7.0.132:46213', 'tcp://10.7.0.133:33183', 'tcp://10.7.0.133:33725', 'tcp://10.7.0.133:35133', 'tcp://10.7.0.133:35484', 'tcp://10.7.0.133:36641', 'tcp://10.7.0.133:36816', 'tcp://10.7.0.133:36875', 'tcp://10.7.0.133:37784', 'tcp://10.7.0.133:38263', 'tcp://10.7.0.133:38746', 'tcp://10.7.0.133:39070', 'tcp://10.7.0.133:39363', 'tcp://10.7.0.133:41171', 'tcp://10.7.0.133:41406', 'tcp://10.7.0.133:41646', 'tcp://10.7.0.133:41908', 'tcp://10.7.0.133:41959', 'tcp://10.7.0.133:42709', 'tcp://10.7.0.133:42952', 'tcp://10.7.0.133:43021', 'tcp://10.7.0.133:43248', 'tcp://10.7.0.133:43271', 'tcp://10.7.0.133:43826', 'tcp://10.7.0.133:45003', 'tcp://10.7.0.133:45124', 'tcp://10.7.0.133:46089', 'tcp://10.7.0.133:46204', 'tcp://10.7.0.133:46213', 'tcp://10.7.0.133:46453', 'tcp://10.7.0.133:46808']
dask.array<concatenate, shape=(12, 16384, 16384), dtype=float64, chunksize=(1, 8192, 8192), chunktype=numpy.ndarray>
Generated contract {'global_t': [(0, 12, 1)]}
Contract has been signed
Original arrays deleted
EST_ANALYTICS_TIME:  100.86105
Done
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: 'tcp://10.7.0.129:8786' processes=60 threads=2400, memory=9.38 TiB>>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/client.py", line 1099, in _heartbeat
    self.scheduler_comm.send({"op": "heartbeat-client"})
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Client->Scheduler local=tcp://10.7.0.129:39722 remote=tcp://10.7.0.129:8786> already closed.

functions called:
SIMULATION_TIME:     106.809095857000017 (avg: 8.900757988083335)
PDI_DELAY:           19.580554321000001 (avg: 1.631712860083333)
SIM_WTHOUT_PDI:      87.228541536000023 (avg: 7.269045128000002)
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://10.7.0.136:58840 remote=tcp://10.7.0.129:8786>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://10.7.0.135:40132 remote=tcp://10.7.0.129:8786>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://10.7.0.135:40134 remote=tcp://10.7.0.129:8786>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
distributed.batched - INFO - Batched Comm Closed <TCP (closed) Client->Scheduler local=tcp://10.7.0.136:58842 remote=tcp://10.7.0.129:8786>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/comm/tcp.py", line 248, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
SUCCESS
HTML_ANALYTICS_TIME:      99.22
HTML_TRANSFER_TIME:       138.26
HTML_DESERIALIZE_TIME:    2.35
HTML_COMPUTE_TIME:        37.70
