Slurm job started at 15/06/2023_21:57:50

NNODES = 6
SIMUNODES = 4
WORKERNODES = 2
NPROC = 128
NWORKER = 60
.....['tcp://10.7.0.140:33256', 'tcp://10.7.0.140:33375', 'tcp://10.7.0.140:33396', 'tcp://10.7.0.140:33681', 'tcp://10.7.0.140:33759', 'tcp://10.7.0.140:34696', 'tcp://10.7.0.140:34785', 'tcp://10.7.0.140:34964', 'tcp://10.7.0.140:35062', 'tcp://10.7.0.140:35460', 'tcp://10.7.0.140:36263', 'tcp://10.7.0.140:36272', 'tcp://10.7.0.140:37092', 'tcp://10.7.0.140:38832', 'tcp://10.7.0.140:38875', 'tcp://10.7.0.140:39356', 'tcp://10.7.0.140:39594', 'tcp://10.7.0.140:40065', 'tcp://10.7.0.140:40285', 'tcp://10.7.0.140:40607', 'tcp://10.7.0.140:40888', 'tcp://10.7.0.140:41159', 'tcp://10.7.0.140:41641', 'tcp://10.7.0.140:42185', 'tcp://10.7.0.140:42387', 'tcp://10.7.0.140:43462', 'tcp://10.7.0.140:44170', 'tcp://10.7.0.140:44664', 'tcp://10.7.0.140:45231', 'tcp://10.7.0.140:45765', 'tcp://10.7.0.141:33480', 'tcp://10.7.0.141:33552', 'tcp://10.7.0.141:34343', 'tcp://10.7.0.141:34989', 'tcp://10.7.0.141:35707', 'tcp://10.7.0.141:36443', 'tcp://10.7.0.141:36600', 'tcp://10.7.0.141:37059', 'tcp://10.7.0.141:37074', 'tcp://10.7.0.141:37263', 'tcp://10.7.0.141:37997', 'tcp://10.7.0.141:38243', 'tcp://10.7.0.141:38783', 'tcp://10.7.0.141:39502', 'tcp://10.7.0.141:41017', 'tcp://10.7.0.141:41161', 'tcp://10.7.0.141:41404', 'tcp://10.7.0.141:41480', 'tcp://10.7.0.141:42244', 'tcp://10.7.0.141:43043', 'tcp://10.7.0.141:43120', 'tcp://10.7.0.141:43273', 'tcp://10.7.0.141:43520', 'tcp://10.7.0.141:43617', 'tcp://10.7.0.141:44348', 'tcp://10.7.0.141:44730', 'tcp://10.7.0.141:44834', 'tcp://10.7.0.141:45132', 'tcp://10.7.0.141:45252', 'tcp://10.7.0.141:45523']
dask.array<concatenate, shape=(25, 2048, 8192), dtype=float64, chunksize=(1, 256, 512), chunktype=numpy.ndarray>
Generated contract {'global_t': [(0, 25, 1)]}
Contract has been signed
Original arrays deleted
TOTAL_SIM_TIME:      19.156327563000001 (avg: 0.766253102520000)
SIM_BLOCK_TIME:      17.370333986000002 (avg: 0.694813359440000)
SIM_WTH_BLOCK:       1.785993576999999 (avg: 0.071439743080000)
SUCCESS
EST_TIME:            62.79123
Done
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: 'tcp://10.7.0.129:8786' processes=60 threads=2400, memory=9.38 TiB>>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/client.py", line 1099, in _heartbeat
    self.scheduler_comm.send({"op": "heartbeat-client"})
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Client->Scheduler local=tcp://10.7.0.129:46998 remote=tcp://10.7.0.129:8786> already closed.

functions called:
ANALYTICS_TIME:      59.45
TRANSFER_TIME:       13.59
DESERIALIZE_TIME:    88.50
COMPUTE_TIME:        9.42
