Slurm job started at 15/06/2023_19:28:16

NNODES = 8
SIMUNODES = 4
WORKERNODES = 4
NPROC = 8
NWORKER = 120
...['tcp://10.7.0.142:33154', 'tcp://10.7.0.142:33333', 'tcp://10.7.0.142:33608', 'tcp://10.7.0.142:33965', 'tcp://10.7.0.142:36692', 'tcp://10.7.0.142:37224', 'tcp://10.7.0.142:37646', 'tcp://10.7.0.142:38547', 'tcp://10.7.0.142:40058', 'tcp://10.7.0.142:40332', 'tcp://10.7.0.142:41129', 'tcp://10.7.0.142:41320', 'tcp://10.7.0.142:41525', 'tcp://10.7.0.142:41592', 'tcp://10.7.0.142:41639', 'tcp://10.7.0.142:41760', 'tcp://10.7.0.142:42120', 'tcp://10.7.0.142:42181', 'tcp://10.7.0.142:42677', 'tcp://10.7.0.142:43856', 'tcp://10.7.0.142:44043', 'tcp://10.7.0.142:44154', 'tcp://10.7.0.142:44301', 'tcp://10.7.0.142:44625', 'tcp://10.7.0.142:45188', 'tcp://10.7.0.142:45705', 'tcp://10.7.0.142:46286', 'tcp://10.7.0.142:46398', 'tcp://10.7.0.142:46573', 'tcp://10.7.0.142:46795', 'tcp://10.7.0.144:33747', 'tcp://10.7.0.144:34418', 'tcp://10.7.0.144:35387', 'tcp://10.7.0.144:35600', 'tcp://10.7.0.144:36003', 'tcp://10.7.0.144:36890', 'tcp://10.7.0.144:36923', 'tcp://10.7.0.144:37145', 'tcp://10.7.0.144:37700', 'tcp://10.7.0.144:38275', 'tcp://10.7.0.144:38454', 'tcp://10.7.0.144:38620', 'tcp://10.7.0.144:39147', 'tcp://10.7.0.144:39279', 'tcp://10.7.0.144:39909', 'tcp://10.7.0.144:40109', 'tcp://10.7.0.144:40360', 'tcp://10.7.0.144:40527', 'tcp://10.7.0.144:41305', 'tcp://10.7.0.144:41306', 'tcp://10.7.0.144:43279', 'tcp://10.7.0.144:43433', 'tcp://10.7.0.144:43464', 'tcp://10.7.0.144:43771', 'tcp://10.7.0.144:45265', 'tcp://10.7.0.144:45803', 'tcp://10.7.0.144:45805', 'tcp://10.7.0.144:45899', 'tcp://10.7.0.144:46163', 'tcp://10.7.0.144:46291', 'tcp://10.7.0.145:33117', 'tcp://10.7.0.145:33139', 'tcp://10.7.0.145:33791', 'tcp://10.7.0.145:34149', 'tcp://10.7.0.145:34210', 'tcp://10.7.0.145:34831', 'tcp://10.7.0.145:35633', 'tcp://10.7.0.145:35839', 'tcp://10.7.0.145:35944', 'tcp://10.7.0.145:36178', 'tcp://10.7.0.145:36310', 'tcp://10.7.0.145:36723', 'tcp://10.7.0.145:36724', 'tcp://10.7.0.145:36927', 'tcp://10.7.0.145:36988', 'tcp://10.7.0.145:37001', 'tcp://10.7.0.145:38442', 'tcp://10.7.0.145:38512', 'tcp://10.7.0.145:38687', 'tcp://10.7.0.145:39040', 'tcp://10.7.0.145:39838', 'tcp://10.7.0.145:40647', 'tcp://10.7.0.145:41811', 'tcp://10.7.0.145:42857', 'tcp://10.7.0.145:43871', 'tcp://10.7.0.145:44840', 'tcp://10.7.0.145:44932', 'tcp://10.7.0.145:45107', 'tcp://10.7.0.145:45268', 'tcp://10.7.0.145:46653', 'tcp://10.7.0.146:33138', 'tcp://10.7.0.146:33345', 'tcp://10.7.0.146:33645', 'tcp://10.7.0.146:33733', 'tcp://10.7.0.146:34286', 'tcp://10.7.0.146:35049', 'tcp://10.7.0.146:35209', 'tcp://10.7.0.146:35429', 'tcp://10.7.0.146:35718', 'tcp://10.7.0.146:36035', 'tcp://10.7.0.146:36141', 'tcp://10.7.0.146:36669', 'tcp://10.7.0.146:37802', 'tcp://10.7.0.146:38608', 'tcp://10.7.0.146:38796', 'tcp://10.7.0.146:39158', 'tcp://10.7.0.146:39204', 'tcp://10.7.0.146:39820', 'tcp://10.7.0.146:40992', 'tcp://10.7.0.146:41266', 'tcp://10.7.0.146:41324', 'tcp://10.7.0.146:41496', 'tcp://10.7.0.146:42599', 'tcp://10.7.0.146:43717', 'tcp://10.7.0.146:43789', 'tcp://10.7.0.146:43849', 'tcp://10.7.0.146:44319', 'tcp://10.7.0.146:45882', 'tcp://10.7.0.146:46080', 'tcp://10.7.0.146:46283']
dask.array<concatenate, shape=(12, 16384, 32768), dtype=float64, chunksize=(1, 8192, 8192), chunktype=numpy.ndarray>
Generated contract {'global_t': [(0, 12, 1)]}
Contract has been signed
Original arrays deleted
EST_TIME:            100.66931
Done
tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: 'tcp://10.7.0.141:8786' processes=120 threads=4800, memory=18.75 TiB>>
Traceback (most recent call last):
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-tornado-6.2-lemkpcoofzciypjtwijrfhbso5bboah2/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/client.py", line 1099, in _heartbeat
    self.scheduler_comm.send({"op": "heartbeat-client"})
  File "/gpfs/users/fernandezx/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/py-distributed-deisa-tvck22hdjddjrkrb4clzsednvt2igzro/lib/python3.10/site-packages/distributed/batched.py", line 136, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Client->Scheduler local=tcp://10.7.0.141:48610 remote=tcp://10.7.0.141:8786> already closed.

functions called:
ANALYTICS_TIME:      99.03
TRANSFER_TIME:       227.75
DESERIALIZE_TIME:    5.15
COMPUTE_TIME:        72.70
